### ISSUE TITLE
PbConsensus Crashes on Out of Bounds Mutations

### ISSUE THREAD

**Issue by bnbowman** [PacificBiosciences/ConsensusCore#11]
The crash from Bug #28955 appears to come from out-of-bounds mutations testing in Template::Mutate - ocassionally mutStart/mutEnd can be slightly larger than tpl_.size(), causing the indexing in tpl_ to reach out of bounds and into random memory and tripping on the assert-statement at the end of the function.  

I've posted a temporary fix that catches those cases and returns boost::none, but the original cause of the out-of-bounds values should probably be investigated further.

**Comment by dalexander** [comment]
This bug report belongs under ConsensusCore2
