### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by lennythomas** [PacificBiosciences/ConsensusCore#3]
When compiling in my debian system I keep getting this error

ConsensusCore configuration summary
-----------------------------------
    BOOST          = /usr/include/
    SWIG           = /usr/bin/swig
    SWIG_LIB       = /usr/share/swig2.0
    PYTHON_INCLUDE = /usr/local/include/python2.7
    NUMPY_INCLUDE  = /usr/local/lib/python2.7/site-packages/numpy/core/include
    DEBUG          = 

....

g++  -O3 -DNDEBUG -g  -msse3 -fPIC -fno-omit-frame-pointer -I/usr/src/app/ConsensusCore/src/C++ -I/usr/src/app/ConsensusCore/external -isystem /usr/include/ -pthread -shared -Wl,-O1 -I/usr/src/app/ConsensusCore/src/C++ -I/usr/src/app/ConsensusCore/external -I /usr/local/include/python2.7 -I /usr/local/lib/python2.7/site-packages/numpy/core/include /usr/src/app/ConsensusCore/build/Python/ConsensusCore_wrap.cxx /usr/src/app/ConsensusCore/build/C++/libConsensusCore.a -o /usr/src/app/ConsensusCore/build/Python/_ConsensusCore.so
In file included from /usr/src/app/ConsensusCore/build/Python/ConsensusCore_wrap.cxx:3694:0:
/usr/src/app/ConsensusCore/src/C++/Interval.hpp:101:27: error: ‘vector’ in namespace ‘std’ does not name a template type
     RangeUnion(const std::vector<Interval> ranges)
                           ^
/usr/src/app/ConsensusCore/src/C++/Interval.hpp:101:33: error: expected ‘,’ or ‘...’ before ‘<’ token
     RangeUnion(const std::vector<Interval> ranges)
                                 ^
In file included from /usr/src/app/ConsensusCore/src/C++/Utils.hpp:44:0,
                 from /usr/src/app/ConsensusCore/src/C++/Interval.hpp:45,
                 from /usr/src/app/ConsensusCore/build/Python/ConsensusCore_wrap.cxx:3694:
/usr/src/app/ConsensusCore/src/C++/Interval.hpp: In function ‘ConsensusCore::Interval ConsensusCore::RangeUnion(int)’:
/usr/src/app/ConsensusCore/src/C++/Interval.hpp:104:37: error: ‘ranges’ was not declared in this scope
         foreach (const Interval& r, ranges)
                                     ^
/usr/src/app/ConsensusCore/src/C++/Interval.hpp:104:9: note: in expansion of macro ‘foreach’
         foreach (const Interval& r, ranges)
         ^
/usr/src/app/ConsensusCore/build/Python/ConsensusCore_wrap.cxx: In function ‘PyObject* _wrap_RangeUnion__SWIG_3(PyObject*, PyObject*)’:
/usr/src/app/ConsensusCore/build/Python/ConsensusCore_wrap.cxx:9151:42: error: no matching function for call to ‘RangeUnion(std::vector<ConsensusCore::Interval, std::allocator<ConsensusCore::Interval> >&)’
   result = ConsensusCore::RangeUnion(arg1);
                                          ^
/usr/src/app/ConsensusCore/build/Python/ConsensusCore_wrap.cxx:9151:42: note: candidates are:
In file included from /usr/src/app/ConsensusCore/build/Python/ConsensusCore_wrap.cxx:3694:0:
/usr/src/app/ConsensusCore/src/C++/Interval.hpp:79:5: note: ConsensusCore::Interval ConsensusCore::RangeUnion(const ConsensusCore::Interval&, const ConsensusCore::Interval&)
     RangeUnion(const Interval& range1, const Interval& range2)
     ^
/usr/src/app/ConsensusCore/src/C++/Interval.hpp:79:5: note:   candidate expects 2 arguments, 1 provided
/usr/src/app/ConsensusCore/src/C++/Interval.hpp:86:5: note: ConsensusCore::Interval ConsensusCore::RangeUnion(const ConsensusCore::Interval&, const ConsensusCore::Interval&, const ConsensusCore::Interval&)
     RangeUnion(const Interval& range1, const Interval& range2,
     ^
/usr/src/app/ConsensusCore/src/C++/Interval.hpp:86:5: note:   candidate expects 3 arguments, 1 provided
/usr/src/app/ConsensusCore/src/C++/Interval.hpp:93:5: note: ConsensusCore::Interval ConsensusCore::RangeUnion(const ConsensusCore::Interval&, const ConsensusCore::Interval&, const ConsensusCore::Interval&, const ConsensusCore::Interval&)
     RangeUnion(const Interval& range1, const Interval& range2,
     ^
/usr/src/app/ConsensusCore/src/C++/Interval.hpp:93:5: note:   candidate expects 4 arguments, 1 provided
/usr/src/app/ConsensusCore/src/C++/Interval.hpp:101:5: note: ConsensusCore::Interval ConsensusCore::RangeUnion(int)
     RangeUnion(const std::vector<Interval> ranges)
     ^
/usr/src/app/ConsensusCore/src/C++/Interval.hpp:101:5: note:   no known conversion for argument 1 from ‘std::vector<ConsensusCore::Interval, std::allocator<ConsensusCore::Interval> >’ to ‘int’
make/Python.mk:19: recipe for target '/usr/src/app/ConsensusCore/build/Python/_ConsensusCore.so' failed

If I run ./configure and then make it compiles just fine, but then GenomicConsensus complains it can't find the python library.

**Comment by mchaisso** [comment]
According to David patch will emerge, in the interim, add 
#include <vector> to Interval.hpp

**Comment by lennythomas** [comment]
Thanks for the quick response. So I am adding

#include <what?>

to 

https://github.com/PacificBiosciences/ConsensusCore/blob/master/src/C%2B%2B/Interval.hpp

Just not sure what I am including. Thanks.

**Comment by mchaisso** [comment]
Not sure why the vector part got clipped off, the correct line to add is:

#include <vector>
at line 44

**Comment by lennythomas** [comment]
Thanks. Will give it a shot.

**Comment by lennythomas** [comment]
That worked. Thanks again.

**Comment by dalexander** [comment]
apologies. I have pushed the fix, along with other stuff
