### ISSUE TITLE
install error in centos 5

### ISSUE THREAD

**Issue by orangeSi** [PacificBiosciences/ConsensusCore#6]
Hi, I meet an error in centos 5:
ConsensusCore/include/ConsensusCore/Matrix/SparseMatrix-inl.hpp:211:15: error: 'runtime_error' is not a member of 'std'
         throw std::runtime_error("cannot perform Get4 with non-f32 type");

And my configure is :( and I use gcc-4.9.0 )
     -----------------------------------
    BOOST          = /opt/blc/boost-1.51.0/include/
    SWIG           = /share/backup/sikaiwei/sikaiwei/assembly/ccs/swig-2.0.12/bin/swig
    SWIG_LIB       = /share/backup/sikaiwei/sikaiwei/assembly/ccs/swig-2.0.12/share/swig/2.0.12
    PYTHON_INCLUDE = /share/backup/sikaiwei/sikaiwei/assembly/ectool/Python-2.7.9/include/python2.7
    NUMPY_INCLUDE  = /share/backup/sikaiwei/sikaiwei/assembly/ectool/Python-2.7.9/lib/python2.7/site-packages/numpy/core/include
    DEBUG          = 1
    CPP_ABI        = c++11

**Comment by dalexander** [comment]
I think this bas probably a missing header.  Did you figure it out?

**Comment by orangeSi** [comment]
I used https://github.com/PacificBiosciences/ConsensusCore/archive/1.0.0.tar.gz and I got that error.
But when I use https://github.com/PacificBiosciences/ConsensusCore/archive/smrtanalysis-2.3.tar.gz ,then error gone ..I don't know how it happen ..
