### ISSUE TITLE
SNR Convenience Functions

### ISSUE THREAD

**Issue by bnbowman** [PacificBiosciences/ConsensusCore#7]
Could we get back some of the convenience functions we used to have in Arrow for working with SNR objects in PbConsensus? Specifically:
(1) Auto-conversion from a vector of floats/doubles to SNR
(2) An easy way to find the minimum value in the struct

**Comment by evolvedmicrobe** [comment]
+1

**Comment by dalexander** [comment]
This bug report belongs under ConsensusCore2
