### ISSUE TITLE
PBConsensus Assertion Error in Template.cpp when called by LAA

### ISSUE THREAD

**Issue by bnbowman** [PacificBiosciences/ConsensusCore#8]
On the Phi29 data-set:

"""
BBOWMAN-MAC:LAA_tests bbowman$ rm -rf amplicon_analysis*; time ./laa phi29.tiny.bam -l 1500
Preprocessing files for Barcode pairs ... done, found 3, took 0.025s
>|> 20151008 19:12:03.308 -|- INFO       -|- DataSet at /Users/bbowman/git/variant_calling/pblaa/src/DataSet.cpp:48 -|- 0x7fff753d2300|| -|- Barcode '0--0', beginning subread filtering
>|> 20151008 19:12:03.340 -|- INFO       -|- DataSet at /Users/bbowman/git/variant_calling/pblaa/src/DataSet.cpp:111 -|- 0x7fff753d2300|| -|- Barcode '0--0', filtered from 305 total subreads
>|> 20151008 19:12:03.340 -|- INFO       -|- DataSet at /Users/bbowman/git/variant_calling/pblaa/src/DataSet.cpp:113 -|- 0x7fff753d2300|| -|- Barcode '0--0', found 78 post-filter subreads
>|> 20151008 19:12:03.340 -|- INFO       -|- DataSet at /Users/bbowman/git/variant_calling/pblaa/src/DataSet.cpp:115 -|- 0x7fff753d2300|| -|- Barcode '0--0', subread filtering took 0.031s
>|> 20151008 19:12:03.394 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:140 -|- 0x7fff753d2300|| -|- Barcode '0--0', aligning 78 subreads
>|> 20151008 19:12:04.086 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:200 -|- 0x7fff753d2300|| -|- Barcode '0--0', subread alignment took 0.692s
>|> 20151008 19:12:04.086 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:202 -|- 0x7fff753d2300|| -|- Barcode '0--0', coarse clustering on alignment results
>|> 20151008 19:12:04.116 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:213 -|- 0x7fff753d2300|| -|- Barcode '0--0', coarse clustering took 0.029s
>|> 20151008 19:12:04.116 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:215 -|- 0x7fff753d2300|| -|- Barcode '0--0', coarse clustering generated 1 clusters
>|> 20151008 19:12:04.116 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:217 -|- 0x7fff753d2300|| -|- Barcode '0--0', ranking subreads on clustering results
>|> 20151008 19:12:04.251 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:245 -|- 0x7fff753d2300|| -|- Barcode '0--0', subread ranking took 0.134s
>|> 20151008 19:12:04.254 -|- INFO       -|- GeneClusterConsensus at /Users/bbowman/git/variant_calling/pblaa/src/Consensus.cpp:316 -|- 0x7fff753d2300|| -|- Barcode '0--0', analyzing clustering results
>|> 20151008 19:12:04.254 -|- INFO       -|- SingleClusterConsensus at /Users/bbowman/git/variant_calling/pblaa/src/Consensus.cpp:259 -|- 0x7fff753d2300|| -|- Barcode '0--0', analyzing Cluster #0
end  ==  1924 
start  ==  4 
end-start  ==  1920 
tpl_.size  ==  1924
Assertion failed: (end_ - start_ == tpl_.size()), function Template, file /Users/bbowman/git/variant_calling/pbconsensus/src/Template.cpp, line 103.
>|> 20151008 19:12:21.516 -|- FATAL      -|- operator() at /Users/bbowman/git/variant_calling/pblaa/../pbccs/include/pacbio/ccs/Logging.h:337 -|- 0x7fff753d2300|| -|- caught SIGABRT
Abort trap: 6
"""

**Comment by bnbowman** [comment]
Same problem on the HLA haploid data set:

"""
BBOWMAN-MAC:LAA_tests bbowman$ rm -rf amplicon_analysis*; time ./laa hla.haploid.bam 
Preprocessing files for Barcode pairs ... done, found 2, took 0.041s
>|> 20151008 19:26:39.263 -|- INFO       -|- DataSet at /Users/bbowman/git/variant_calling/pblaa/src/DataSet.cpp:48 -|- 0x7fff753d2300|| -|- Barcode '53--53', beginning subread filtering
>|> 20151008 19:26:39.346 -|- INFO       -|- DataSet at /Users/bbowman/git/variant_calling/pblaa/src/DataSet.cpp:111 -|- 0x7fff753d2300|| -|- Barcode '53--53', filtered from 438 total subreads
>|> 20151008 19:26:39.346 -|- INFO       -|- DataSet at /Users/bbowman/git/variant_calling/pblaa/src/DataSet.cpp:113 -|- 0x7fff753d2300|| -|- Barcode '53--53', found 220 post-filter subreads
>|> 20151008 19:26:39.346 -|- INFO       -|- DataSet at /Users/bbowman/git/variant_calling/pblaa/src/DataSet.cpp:115 -|- 0x7fff753d2300|| -|- Barcode '53--53', subread filtering took 0.082s
>|> 20151008 19:26:39.545 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:140 -|- 0x7fff753d2300|| -|- Barcode '53--53', aligning 220 subreads
>|> 20151008 19:26:43.504 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:200 -|- 0x7fff753d2300|| -|- Barcode '53--53', subread alignment took 3.958s
>|> 20151008 19:26:43.504 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:202 -|- 0x7fff753d2300|| -|- Barcode '53--53', coarse clustering on alignment results
>|> 20151008 19:26:43.970 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:213 -|- 0x7fff753d2300|| -|- Barcode '53--53', coarse clustering took 0.465s
>|> 20151008 19:26:43.970 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:215 -|- 0x7fff753d2300|| -|- Barcode '53--53', coarse clustering generated 6 clusters
>|> 20151008 19:26:43.970 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:217 -|- 0x7fff753d2300|| -|- Barcode '53--53', ranking subreads on clustering results
>|> 20151008 19:26:45.209 -|- INFO       -|- GeneCluster at /Users/bbowman/git/variant_calling/pblaa/src/GeneCluster.cpp:245 -|- 0x7fff753d2300|| -|- Barcode '53--53', subread ranking took 1.239s
>|> 20151008 19:26:45.215 -|- INFO       -|- GeneClusterConsensus at /Users/bbowman/git/variant_calling/pblaa/src/Consensus.cpp:316 -|- 0x7fff753d2300|| -|- Barcode '53--53', analyzing clustering results
>|> 20151008 19:26:45.215 -|- INFO       -|- SingleClusterConsensus at /Users/bbowman/git/variant_calling/pblaa/src/Consensus.cpp:259 -|- 0x7fff753d2300|| -|- Barcode '53--53', analyzing Cluster #0
3445 0 3445 3445
3445 0 3445 3445
3445 0 3445 3445
3444 0 3444 3445
Assertion failed: (end_ - start_ == tpl_.size()), function Template, file /Users/bbowman/git/variant_calling/pbconsensus/src/Template.cpp, line 103.
>|> 20151008 19:27:46.131 -|- FATAL      -|- operator() at /Users/bbowman/git/variant_calling/pblaa/../pbccs/include/pacbio/ccs/Logging.h:337 -|- 0x7fff753d2300|| -|- caught SIGABRT
Abort trap: 6
"""

**Comment by dalexander** [comment]
This bug report belongs under ConsensusCore2
